### ISSUE TITLE
dashboard: timemachineでエラーが正確に表示できない

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-frontend#16]
```python
python Traceback (most recent call last):
File "/home/tasuren/.local/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
 ret = await coro(*args, **kwargs) 
File "/home/tasuren/rt/rt-bot/rtlib/slash.py", line 66, in new_function
 return await original_function(*args, **kwargs)
File "/home/tasuren/rt/rt-bot/cogs/server_tool.py", line 259, in timemachine
 raise discord.HTTPException("さかのぼりすぎた。")
TypeError: __init__() missing 1 required positional argument: 'message'
```
引数に500を指定したら出た。

**Comment by tasuren** [comment]
ダッシュボード関係なく起きるっぽい。

**Comment by tasuren** [comment]
修正した。
